disabled_rules: # 禁用指定的规则
  - colon
  - comma
  - control_statement
  - line_length
  - identifier_name
  - multiple_closures_with_trailing_closure
opt_in_rules: # 启用指定的规则
  - empty_count
  - missing_docs
  # 可以通过执行如下指令来查找所有可用的规则:
  # swiftlint rules
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Pods

